#page title
page_title                                : QuoteFlow                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6740753999                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : QuoteFlow                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The ultimate tool for book lovers and quote enthusiasts! Track books you're reading, plan what to read next, and revisit the ones you've completed. Save memorable quotes from your favorite books, organize them with tags, and view them in your personalized feed.                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jonathan Young                                
your_link                                 : https://jonathanyoung.dev                     
your_city                                 :                                 
email_address                             : feedbackquoteflow@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Track Your Reading Journey
    description                           : Easily manage books you've read, are currently reading, or plan to read. Organize your reading list effortlessly.
    fontawesome_icon_name                 : book
    
  - title                                 : Capture Favorite Quotes
    description                           : Save memorable quotes from your books and revisit them anytime in your personal quote feed.
    fontawesome_icon_name                 : quote-left

  - title                                 : Scroll Through Your Quote Feed
    description                           : Easily browse and reflect on the quotes you've saved from your books in a personalized, scrollable feed.
    fontawesome_icon_name                 : quote-right

  - title                                 : Add Books by ISBN or Online
    description                           : Quickly add books by scanning their ISBN or searching for them online, so you can grow your library with ease.
    fontawesome_icon_name                 : barcode

  - title                                 : Organize with Collections
    description                           : Sort books into custom collections and add tags to group your favorite quotes for quick access.
    fontawesome_icon_name                 : folder

  - title                                 : Set Reading Reminders
    description                           : Stay on top of your reading goals by setting reminders to keep you motivated and on track.
    fontawesome_icon_name                 : bell
  
  - title                                 : Widgets for Quick Access
    description                           : Access your books and quotes right from your home screen with convenient widgets that keep your reading at your fingertips.
    fontawesome_icon_name                 : bolt

  - title                                 : Manage Your Quotes with Tags
    description                           : Organize your favorite quotes by adding custom tags, making it simple to group and find them when you need inspiration.
    fontawesome_icon_name                 : tags

  - title                                 : Continuous Development from a Single Developer
    description                           : QuoteFlow is a passion project developed by a single developer, so you can expect regular updates and improvements.
    fontawesome_icon_name                 : tags

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
